version: "3.9"
services:
  db:
    image: postgres:13-buster
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    ports:
    - 5432:5432
  queue:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
  job:
    build: .
    depends_on:
      - db
    entrypoint: "/app/job"
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      PORT: "8080"
      POSTGRES_CONNECTION_STRING: "postgres://user:pass@db:5432/job?sslmode=disable"
  trigger:
    build: .
    entrypoint: "/app/trigger"
    depends_on:
      - queue
      - job
    environment:
      RABBITMQ_CONNECTION_STRING: "amqp://queue:5672"
      JOB_CONNECTION_STRING: "http://job:8080"
  command-run:
    build: .
    entrypoint: "/app/command-run"
    depends_on:
      - queue
    environment:
      RABBITMQ_CONNECTION_STRING: "amqp://queue:5672"
  result:
    build: .
    entrypoint: "/app/result"
    depends_on:
      - queue
      - db
    environment:
      RABBITMQ_CONNECTION_STRING: "amqp://queue:5672"
      POSTGRES_CONNECTION_STRING: "postgres://user:pass@db:5432/job?sslmode=disable"
