version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres:13-buster
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    ports:
    - 5432:5432
  queue:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
