### Create new job
POST http://localhost:8080/
Content-Type: application/json

{
  "name": "test01",
  "command": "curl"
}

### List job
GET http://localhost:8080/
Content-Type: application/json

### Get job
GET http://localhost:8080/299c3787-4f40-4218-9acd-ad98a40f7e63
Content-Type: application/json

### Update job
PUT http://localhost:8080/299c3787-4f40-4218-9acd-ad98a40f7e63
Content-Type: application/json

{
  "name": "test02",
  "command": "curl"
}
