
### Create new job
POST {{host}}/
Content-Type: application/json

{
  "name": "test01",
  "command": "curl"
}

### List job
GET {{host}}/
Content-Type: application/json

### Get job
GET {{host}}/4daacde2-af16-4df6-a295-a7c483b9ce5c
Content-Type: application/json

### Update job
PUT {{host}}/fa972dc9-0927-4263-9b11-f384ce217ce7
Content-Type: application/json

{
  "name": "test02",
  "command": "https://example.com/"
}
