image:
  repository: "docker.io/library/curl-monitor"
  pullPolicy: IfNotPresent
  tag: "1.3.0"
  command:
    - "/app/command-run"

migration:
  enabled: false

nameOverride: command-run

env:
  - name: PORT
    value: "8080"
  - name: HEALTHCHECK_PORT
    value: "8081"
  - name: RABBITMQ_CONNECTION_STRING
    value: "amqp://guest:guest@rabbitmq.default:5672"
