image:
  repository: "docker.io/library/curl-monitor"
  pullPolicy: IfNotPresent
  tag: "1.3.2"
  command:
    - "/app/job"

service:
  nodePort: 30200

nameOverride: job

env:
  - name: PORT
    value: "8080"
  - name: HEALTHCHECK_PORT
    value: "8081"
  - name: POSTGRES_CONNECTION_STRING
    value: "postgres://user:pass@postgres-postgresql.default:5432/postgres?sslmode=disable"

migration:
  enabled: true
  args:
    - "migrate"
    - "-path=/migrations/"
    - "-database=postgres://user:pass@postgres-postgresql.default:5432/postgres?sslmode=disable"
    - "up"
