image:
  repository: "docker.io/library/curl-monitor"
  pullPolicy: IfNotPresent
  tag: "1.3.2"
  command:
    - "/app/result"

migration:
  enabled: false

nameOverride: result

env:
  - name: PORT
    value: "8080"
  - name: HEALTHCHECK_PORT
    value: "8081"
  - name: RABBITMQ_CONNECTION_STRING
    value: "amqp://guest:guest@rabbitmq.default:5672"
  - name: POSTGRES_CONNECTION_STRING
    value: "postgres://user:pass@postgres-postgresql.default:5432/postgres?sslmode=disable"
