image:
  repository: "docker.io/library/curl-monitor"
  pullPolicy: IfNotPresent
  tag: "1.3.2"
  command:
    - "/app/trigger"

migration:
  enabled: false

nameOverride: trigger

env:
  - name: PORT
    value: "8080"
  - name: HEALTHCHECK_PORT
    value: "8081"
  - name: RABBITMQ_CONNECTION_STRING
    value: "amqp://guest:guest@rabbitmq.default:5672"
  - name: JOB_CONNECTION_STRING
    value: "http://curl-monitor-job:8080"
